// Generated by CoffeeScript 1.10.0
(function() {
  var JSZip, app, bodyParser, express, formidable, fs, io, router, server;

  JSZip = require("jszip");

  bodyParser = require('body-parser');

  formidable = require('formidable');

  express = require('express');

  app = express();

  server = require('http').Server(app);

  io = require('socket.io')(server);

  fs = require("fs");

  router = express.Router();

  router.get('/sockets', function(req, res) {
    return res.json(io.sockets.sockets.map(function(a) {
      return a.id;
    }));
  });

  router.get('/start', function(req, res) {
    res.statusCode = 204;
    res.send();
    return io.sockets.emit("start");
  });

  router.post("/push", function(req, res) {
    var form;
    form = new formidable.IncomingForm();
    form.encoding = "utf-8";
    form.uploadDir = "./uploads";
    form.parse(req, function(err, fields, files) {
      var newPath, oldPath;
      console.log(err, fields, files);
      oldPath = './' + files.file._writeStream.path;
      newPath = './uploads/' + Date.now() + "_" + files.file.name;
      return fs.rename(oldPath, newPath, function(err) {
        if (err) {
          throw err;
        }
      });
    });
    res.statusCode = 204;
    return res.send();
  });

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(bodyParser.json());

  app.use('/demo', express["static"](__dirname + '/../demo'));

  app.use('/api', router);

  io.on('connection', function(socket) {
    console.log("connection", socket.client.id);
    socket.on('echo', function(data) {
      return socket.emit("echo", data);
    });
    socket.on('event', console.info.bind(console, "event"));
    return socket.on('disconnect', console.info.bind(console, "disconnect"));
  });

  server.listen(8000);

}).call(this);
