// Generated by CoffeeScript 1.10.0
var Chord, chord, main, rootNodeId, setup;

Chord = P2PRingNet.Chord;

chord = new Chord({
  host: location.hostname,
  port: location.port,
  path: "peerjs",
  secure: true,
  debug: 3
});

window["chord"] = chord;

rootNodeId = null;

setup = function(next) {
  return next();
};

main = function(next) {
  if (rootNodeId) {
    ord.join(rootNodeId);
  } else {
    chord.create();
  }
  return next();
};

window.addEventListener("DOMContentLoaded", function() {
  return setup(function() {
    return main(function() {
      return console.log("end");
    });
  });
});
