// Generated by CoffeeScript 1.10.0
(function() {
  var actx, n, osc, pn, socket, tse;

  window.navigator["getUserMedia"] = window.navigator.webkitGetUserMedia || window.navigator.mozGetUserMedia || window.navigator.getUserMedia;

  window["socket"] = socket = io(location.hostname + ":" + location.port);

  socket.on("connect", console.info.bind(console, "connect"));

  socket.on("reconnect", console.info.bind(console, "reconnect"));

  socket.on("reconnect_attempt", console.info.bind(console, "reconnect_attempt"));

  socket.on("reconnecting", console.info.bind(console, "reconnecting"));

  socket.on("reconnect_error", console.info.bind(console, "reconnect_error"));

  socket.on("reconnect_failed", console.info.bind(console, "reconnect_failed"));

  socket.on("disconnect", console.info.bind(console, "disconnect"));

  socket.on("error", console.info.bind(console, "error"));

  socket.on("echo", console.info.bind(console, "echo"));

  socket.on("connect", function() {
    return socket.emit("echo", "hello");
  });

  this.view = function(arr, w, h) {
    var _view;
    if (w == null) {
      w = arr.length;
    }
    if (h == null) {
      h = 128;
    }
    _view = new SignalViewer(w, h);
    _view.draw(arr);
    return document.body.appendChild(_view.cnv);
  };

  n = function(a) {
    return a.split("").map(Number);
  };

  actx = new AudioContext();

  osc = new OSC(actx);

  pn = new Float32Array(Signal.mseqGen(11, n("01001001001")));

  tse = new TimeSpreadEcho(actx, kernel);

  tse.processor.connect(actx.destination);

  osc.createAudioBufferFromURL("TellYourWorld1min.mp3").then(function(abuf) {
    var anode;
    anode = osc.createAudioNodeFromAudioBuffer(abuf);
    anode.connect(tse.processor);
    return anode.start(actx.currentTime);
  });

}).call(this);
